#!/usr/bin/env bash
# Merge .env.runtime + .env.models → .env (local) or a deploy target.
#
# Usage:
#   ./scripts/merge-env.sh
#   ./scripts/merge-env.sh /path/to/out.env
#   ENV_RUNTIME=.env.runtime ENV_MODELS=.env.models ./scripts/merge-env.sh
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
RUNTIME="${ENV_RUNTIME:-$ROOT/.env.runtime}"
MODELS="${ENV_MODELS:-$ROOT/.env.models}"
OUT="${1:-$ROOT/.env}"

missing=0
if [[ ! -f "$RUNTIME" ]]; then
  echo "missing runtime env: $RUNTIME (copy from .env.runtime.example)" >&2
  missing=1
fi
if [[ ! -f "$MODELS" ]]; then
  echo "missing models env: $MODELS (copy from .env.models.example)" >&2
  missing=1
fi
if [[ "$missing" -ne 0 ]]; then
  exit 1
fi

{
  echo "# Generated by scripts/merge-env.sh — do not edit by hand."
  echo "# Sources: $RUNTIME + $MODELS"
  echo
  echo "# --- runtime ---"
  cat "$RUNTIME"
  echo
  echo "# --- models ---"
  cat "$MODELS"
} >"$OUT"

echo "wrote $OUT"
